name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  build-android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Clean
        run: |
            cd simple_live_app
            flutter clean
      - name: Build debug APK
        run: |
          cd simple_live_app
          flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-debug-apk
          path: simple_live_app/build/app/outputs/flutter-apk/app-debug.apk
